name: Create new release
on: 
  workflow_dispatch:
    inputs:
      PlaceholderInput:
        description: PlaceholderInput
        required: false
jobs:
  call-release-build:
    uses: ./.github/workflows/build.yml
    with:
      deploymode: release
  deploy:
    name: Deploy release
    runs-on: ubuntu-20.04
    needs: call-release-build
    steps:
      - uses: actions/checkout@v3
 
          
      - uses: actions/download-artifact@v3
        with:
          name: cemu-bin-windows-x64
          path: cemu-bin-windows-x64

      - name: Initialize
        run: |
          mkdir upload
          sudo apt update -qq
          sudo apt install -y zip
          
      - name: Get Cemu release version
        run: |
          gcc -o getversion .github/getversion.cpp
          echo "Cemu CI version: $(./getversion)"
          echo "CEMU_FOLDER_NAME=Cemu_$(./getversion)" >> $GITHUB_ENV
          echo "CEMU_VERSION=$(./getversion)" >> $GITHUB_ENV
          
      - name: Create release from windows-bin
        run: |
          ls ./
          ls ./bin/
          cp -R ./bin ./${{ env.CEMU_FOLDER_NAME }}
          mv cemu-bin-windows-x64/Cemu.exe ./${{ env.CEMU_FOLDER_NAME }}/Cemu.exe
          zip -9 -r upload/cemu-${{ env.CEMU_VERSION }}-windows-x64.zip ${{ env.CEMU_FOLDER_NAME }}
          rm -r ./${{ env.CEMU_FOLDER_NAME }}

         
