name: Deploy experimental release
on: 
  workflow_dispatch:

jobs:
  call-release-build:
    uses: ./.github/workflows/build.yml
    with:
      deploymode: release
      experimentalversion: ${{ github.run_number }}
  deploy:
    name: Deploy experimental release
    runs-on: ubuntu-20.04
    needs: call-release-build
    steps:
      - uses: actions/checkout@v3
 


      - uses: actions/download-artifact@v3
        with:
          name: cemu-bin-windows-x64
          path: cemu-bin-windows-x64



      - name: Initialize
        run: |
          mkdir upload
          sudo apt install zip
          
      - name: Get version
        run: |
          echo "Experimental version: ${{ github.run_number }}"
          ls
          gcc -o getversion .github/getversion.cpp
          ./getversion
          echo "Cemu CI version: $(./getversion)"
          echo "CEMU_FOLDER_NAME=Cemu_$(./getversion)-${{ github.run_number }}" >> $GITHUB_ENV
          echo "CEMU_VERSION=$(./getversion)-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Create release from windows-bin
        run: |
          ls ./
          ls ./bin/
          cp -R ./bin ./${{ env.CEMU_FOLDER_NAME }}
          mv cemu-bin-windows-x64/Cemu.exe ./${{ env.CEMU_FOLDER_NAME }}/Cemu.exe
          zip -9 -r upload/cemu-${{ env.CEMU_VERSION }}-windows-x64.zip ${{ env.CEMU_FOLDER_NAME }}
          rm -r ./${{ env.CEMU_FOLDER_NAME }}

